---
# Este playbook actualiza un ubuntu a la ultima version.

- name: actualizacion de ubuntu
  hosts: all
  environment: 
    http_proxy: http://10.9.35.51:3128
    https_proxy: https://10.9.35.51:3128
    
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Upgrade packages
      apt: 
        upgrade: dist

#    - name: Check if a reboot is required
#      register: reboot_required_file
#      stat: path=/var/run/reboot-required get_md5=no
#
#    - name: restart machine
#      become: yes
#      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#      async: 1
#      poll: 0
#      ignore_errors: true
#      when: reboot_required_file.stat.exists == true
