---

# tasks file

#7.6 Mantenimiento de Sistema

#7.6.1 System File Permissions

  - name: 7.6.1.2 Verificar los permisos del archivo /etc/passwd
    file:
      dest: /etc/passwd
      owner: root
      group: root
      mode: 0644
  
  - name: 7.6.1.3 Verificar los permisos del archivo /etc/shadow
    file:
      dest: /etc/shadow
      owner: root
      group: root
      mode: 0000
       
  - name: 7.6.1.4 Verificar los permisos del archivo /etc/group
    file:
      dest: /etc/group
      owner: root
      group: root
      mode: 0644
        
  - name: 7.6.1.5 Verificar los permisos del archivo /etc/gshadow
    file:
      dest: /etc/gshadow
      owner: root
      group: root
      mode: 0000
      
#7.6.2 Comentarios de configuración de usuarios y grupos.

  - name: 7.6.2.1 Asegurarse que los campos de password no están en blanco
    shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
    register: empty_password_accounts
    failed_when: empty_password_accounts.stdout_lines | length > 0
