---

# tasks file

#7.2 Servicios del Sistema Operativo

#7.2.1 Servicios Inetd
  
  - name: 7.2.1.1 Asegurarse que los servicios chargen NO están habilitados
    command: /usr/sbin/chkconfig chargen-dgram off
    notify: restart xinetd
    
  - name: 7.2.1.1 Asegurarse que los servicios chargen NO están habilitados
    command: /usr/sbin/chkconfig chargen-stream off
    notify: restart xinetd
    
  - name: 7.2.1.2 Asegurarse que los servicios daytime NO están habilitados
    command: /usr/sbin/chkconfig daytime-dgram off
    notify: restart xinetd

#Lo usamos para alarmas    
  - name: 7.2.1.2 Asegurarse que los servicios daytime NO están habilitados
    command: /usr/sbin/chkconfig daytime-stream on
    notify: restart xinetd
  
  - name: 7.2.1.3 Asegurarse que los servicios discard NO están habilitados
    command: /usr/sbin/chkconfig discard-dgram off
    notify: restart xinetd
    
  - name: 7.2.1.3 Asegurarse que los servicios discard NO están habilitados
    command: /usr/sbin/chkconfig discard-stream off
    notify: restart xinetd
  
  - name: 7.2.1.4 Asegurarse que los servicios echo NO están habilitados
    command: /usr/sbin/chkconfig echo-dgram off
    notify: restart xinetd
    
  - name: 7.2.1.4 Asegurarse que los servicios echo NO están habilitados
    command: /usr/sbin/chkconfig echo-stream off
    notify: restart xinetd
  
  - name: 7.2.1.5 Asegurarse que los servicios time NO están habilitados
    command: /usr/sbin/chkconfig time-dgram off
    notify: restart xinetd
    
  - name: 7.2.1.5 Asegurarse que los servicios time NO están habilitados
    command: /usr/sbin/chkconfig time-stream off
    notify: restart xinetd
  
  - name: 7.2.1.6 Asegurarse que los servicios tftp-server NO están habilitados
    block:
      - name: 7.2.1.6 Asegurarse que los servicios tftp-server NO están habilitados
        stat:
          path: /etc/xinetd.d/tftp
        register: tftp_service
      
      - name: 7.2.1.6 Asegurarse que los servicios tftp-server NO están habilitados
        command: /usr/sbin/chkconfig tftp off
        notify: restart xinetd
        when: tftp_service.stat.exists
      
#7.2.2 Servicios especiales 

#7.2.2.1 Sincronización del tiempo

  - name: 7.2.2.1.1 Asegurarse que la sincronización del tiempo esta siendo usada
    yum:
      name: ntp
      state: present
        
  - name: 7.2.2.1.1 Asegurarse que la sincronización del tiempo esta siendo usada
    yum:
      name: chrony
      state: present
        
  - name: 7.2.2.1.1 Asegurarse que la sincronización del tiempo esta siendo usada
    service:
      name: ntpd
      state: started
      enabled: yes
        
  - name: 7.2.2.1.1 Asegurarse que la sincronización del tiempo esta siendo usada
    service:
      name: chronyd
      state: stopped
      enabled: no      

  - name: 7.2.2.1.2 Asegurarse que NTP esta configurado
    template:
      src: templates/ntp.conf.{{hostvars[inventory_hostname].sdp}}.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
      #notify: restart ntpd

  - name: 7.2.2.1.2 Asegurarse que NTP esta configurado
    lineinfile:
      dest: /etc/sysconfig/ntpd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u ntp:ntp\""

  - name: 7.2.2.1.2 Asegurarse que NTP esta configurado
    lineinfile:
      dest: /usr/lib/systemd/system/ntpd.service
      regexp: "^(#)?ExecStart"
      line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
     
  - name: 7.2.2.2 Asegurarse que el sistema X Windows no esta instalado
    yum:
      name: "{{item}}"
      state: absent
    with_items:
      #- "@X Window System"
      #- "xorg-x11*"
      - "httpd*" 

  - name: Traer servicios
    service_facts:
    register: services_list
    
  - name: 7.2.2.3 Verificar que el servidor Avahi este desactivado
    service:
      name: avahi-daemon
      state: stopped
      enabled: no
    when: "'avahi-daemon.service' in services_list.ansible_facts.services"      
        
  - name: 7.2.2.4 Verificar que el print server Cups este desactivado
    service:
      name: cups
      state: stopped
      enabled: no
    when: "'cups.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.5 Verificar que el DHCP Server este desactivado
    service:
      name: dhcpd
      state: stopped
      enabled: no
    when: "'dhcpd.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.6 Verificar que el LDAP Server este desactivado
    service:
      name: slapd
      state: stopped
      enabled: no
    when: "'slapd.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.7 Verificar que NFS y RPC esten desactivados
    service:
      name: nfs
      state: stopped
      enabled: no
    when: "'nfs.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.7 Verificar que NFS y RPC esten desactivados
    service:
      name: rpcbind
      state: stopped
      enabled: no
    when: "'rpcbind.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.8 Verificar que el servidor de DNS este desactivado
    service:
      name: named
      state: stopped
      enabled: no
    when: "'named.service' in services_list.ansible_facts.services"
    
  - name: 7.2.2.9 Verificar que el servidor FTP este desactivado
    service:
      name: vsftpd
      state: stopped
      enabled: no
    when: "'vsftpd.service' in services_list.ansible_facts.services"    
    
  - name: 7.2.2.10 Verificar que el servidor HTTP este desactivado
    service:
      name: httpd
      state: stopped
      enabled: no
    when: "'httpd.service' in services_list.ansible_facts.services"      
  
  - name: 7.2.2.11 Verificar que el servidor IMAP y POP3 esten desactivados
    service:
      name: dovecot
      state: stopped
      enabled: no
    when: "'dovecot.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.12 Verificar que el servidor Samba este desactivado
    service:
      name: smb
      state: stopped
      enabled: no
    when: "'smb.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.13 Verificar que el servidor HTTP Proxy este desactivado
    service:
      name: squid
      state: stopped
      enabled: no
    when: "'squid.service' in services_list.ansible_facts.services"      
    
#Lo usamos para alarmas
  - name: 7.2.2.14 Verificar que el servidor SNMP no este activado
    service:
      name: snmpd
      state: started
      enabled: yes
    when: "'snmpd.service' in services_list.ansible_facts.services"      
  
  - name: 7.2.2.15 Configurar el Mail Tranfer Agent en modo local
    lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
    notify: restart postfix

  - name: 7.2.2.16 Verificar que el servidor NIS no este activado
    service:
      name: ypserv
      state: stopped
      enabled: no
    when: "'ypserv.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.17 Asegurarse que el rsh server no este activado
    service:
      name: rsh.socket
      state: stopped
      enabled: no
    when: "'rsh.socket.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.17 Asegurarse que el rsh server no este activado
    service:
      name: rlogin.socket
      state: stopped
      enabled: no    
    when: "'rlogin.socket.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.17 Asegurarse que el rsh server no este activado
    service:
      name: rexec.socket
      state: stopped
      enabled: no
    when: "'rexec.socket.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.18 Asegurarse que el talk server no este activado
    service:
      name: ntalk
      state: stopped
      enabled: no
    when: "'ntalk.service' in services_list.ansible_facts.services"      
    
  - name: 7.2.2.19 Asegurarse que el telnet server no este activado
    service:
      name: telnet
      state: stopped
      enabled: no
    when: "'telnet.service' in services_list.ansible_facts.services"      
  
  - name: 7.2.2.20 Asegurarse que el tftp server no este activado
    service:
      name: tftp
      state: stopped
      enabled: no
    when: "'tftp.service' in services_list.ansible_facts.services"  
    
  - name: 7.2.2.21 Asegurarse que el servicio rsync no este activado
    service:
      name: rsyncd
      state: stopped
      enabled: no
    when: "'rsyncd.service' in services_list.ansible_facts.services"      

#7.2.2.22 Asegurarse que el servicio AVAHI SERVER no este activado. Idem 7.2.2.3


