---

# tasks file

#7.3 Configuración de Red

#7.3.1 Modificar parámetros de Red (Solo hosts)

  - name: 7.3.1.1 Desactivar IP Forwarding (Server cómo Router)
    sysctl:
      name: net.ipv4.ip_forward
      value: 0
      state: present
      reload: yes
      ignoreerrors: yes
    notify:
      - sysctl flush ipv4 route table      

  - name: 7.3.1.2 Deshabilitar Send Packet Redirects
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
    with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
    notify:
      - sysctl flush ipv4 route table
      
#7.3.2 Modificar parámetros de Red (host y Router)

  - name: 7.3.2.1 Deshabilitar Source Routed Packet Acceptance
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
    with_items:
      - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
      - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    notify:
      - sysctl flush ipv4 route table
      
  - name: 7.3.2.2 Loguear Paquetes sospechosos
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
    with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
    notify:
      - sysctl flush ipv4 route table
  
  - name: 7.3.2.3 Habilitar Ignore Broadcast Requests
    sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
    notify:
      - sysctl flush ipv4 route table
  
  - name: 7.3.2.4 Habilitar protección contra mensajes de error falsos
    sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
    notify:
      - sysctl flush ipv4 route table
  
  - name: 7.3.2.5 Habilitar TCP SYN Cookies
    sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
    notify:
      - sysctl flush ipv4 route table
      
#7.3.3 Wireless Networking

#7.3.4 Desactivar interfaces wireless. Ver manualmente

#7.3.5 IPv6

  - name: 7.3.5.1 Desactivar IPv6
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?options ipv6(\\s|$)"
      line: "options ipv6 disable=1"
      create: yes

#7.3.6 Protocolos de red poco frecuentes

  - name: 7.3.6.1 Desahiblitar DCCP
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install dccp(\\s|$)"
      line: "install dccp /bin/true"
      create: yes
  
  - name: 7.3.6.2 Desahiblitar SCTP
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install sctp(\\s|$)"
      line: "install sctp /bin/true"
      create: yes
  
  - name: 7.3.6.3 Desahiblitar RDS
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install rds(\\s|$)"
      line: "install rds /bin/true"
      create: yes
  
  - name: 7.3.6.4 Desahiblitar TIPC
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install tipc(\\s|$)"
      line: "install tipc /bin/true"
      create: yes
