---

# tasks file

#7.4 Registro y Auditoria (Logging and Auditing)
#7.4.1 Configurar System Accounting (auditd)
#7.4.1.1 Configurar Data Retention
#7.4.1.2 Configurar el tama침o de almacenamiento del registro de auditoria
#7.4.1.3 Habilitar el servicio auditd
#7.4.1.4 Asegurarse que los eventos que modifican la informaci칩n de los archivos m치s
#7.4.2 Configurar rsyslog
#7.4.2.1 Asegurarse que el servicio rsyslog esta activado
#7.4.2.2 Configuraci칩n del rsyslog.conf
#7.4.2.3 Asegurarse que rsyslog esta configurado para enviar logs a SIEM
#7.4.3 Configurar AUTH.DEBUG
