---

# Ejemplo de como usar command
  - name: Ejecutar un comando en un host remoto.
    command: /usr/sbin/getenforce

# Ejemplo de como usar shell
  - name: Ejecutar un comando en una shell remota.
    shell: echo "test shell" >> /tmp/shell.txt

  - name: Apache package
    yum:
      name: httpd
      state: installed
    become: true
    
# Ejemplo de como ver si un paquete esta instalado    
#  - name: Asegurar si los paquetes estan instalados
#    yum:
#      name: "{{ packages }}"
#    become: true
#    vars:
#      packages:
#      - httpd
#      - httpd-tools
   
# Ejemplo de como ver si un servicio esta corriendo   
  - name: Start servicio NTP si no esta levantado
    service:
      name: ntp
      state: running
      
# Ejemplo de como buscar archivos y mostrarlos      
  - name: Busca archivos *repo
    find:
      paths: /etc/yum.repos.d
      patterns: "*.repo"
    register: yum_repos      
  
# Ejemplo de como cambiar permisos de un file
  - name: Cambiar permisos de un file
    file:
      path: /tmp/foo.conf
      owner: rdnovell
      group: rdnovell
      mode: '0644'  