---

# handlers file

  - name: restart xinetd
    service:
      name: xinetd
      state: restarted
      
  - name: restart ntpd
    service:
      name: ntpd
      state: restarted      
      
  - name: restart postfix
    service:
      name: postfix
      state: restarted            
      
  - name: restart sshd
    service:
      name: sshd
      state: restarted                  