---

# tasks file

  - name: Copiar script de usuarios
    template:
      src: templates/script-arch.sh.j2
      dest: /etc/act/script-arch.sh
      owner: root
      group: root
      
  - name: Creacion de usuarios
    script: /etc/act/script-arch.sh

  - name: oracle-recommended sysctl
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      state: present
      ignoreerrors: yes # Ignore errors about unknown keys
    with_items:
      - { name: "kernel.core_uses_pid", value: "0" }
      - { name: "vm.swappiness", value: "10" }
      - { name: "vm.dirty_background_ratio", value: "3" }
      - { name: "vm.dirty_ratio", value: "80" }
      - { name: "vm.dirty_expire_centisecs", value: "500" }
      - { name: "vm.dirty_writeback_centisecs", value: "100" }
      - { name: "kernel.panic", value: "30" }
      - { name: "fs.aio-max-nr", value: "1048576" }
      - { name: "net.core.rmem_default", value: "262144" }
      - { name: "net.core.wmem_default", value: "262144" }
      - { name: "net.core.rmem_max", value: "4194304" }
      - { name: "net.core.wmem_max", value: "1048576" }
      - { name: "net.core.netdev_max_backlog", value: "20000" }
      - { name: "fs.file-max", value: "6815744" }
      - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
      - { name: "net.ipv4.conf.all.accept_source_route", value: "0" }
      - { name: "net.ipv4.conf.all.send_redirects", value: "0" }
      - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" }
      - { name: "net.ipv4.tcp_fin_timeout", value: "30" }
      - { name: "net.ipv4.tcp_keepalive_intvl", value: "15" }
      - { name: "net.ipv4.tcp_keepalive_probes", value: "5" }
      - { name: "net.ipv4.tcp_keepalive_time", value: "300" }
      - { name: "net.ipv4.tcp_retries2", value: "15" }
      - { name: "net.ipv4.route.flush", value: "1" }
      - { name: "net.ipv6.conf.all.disable_ipv6", value: "1" }
      - { name: "net.ipv6.conf.default.disable_ipv6", value: "1" }
      - { name: "kernel.msgmax", value: "300032" }
      - { name: "kernel.printk", value: "3 4 1 7" }
  
  - name: save sysctl config
    command: sysctl -p
    ignore_errors: yes # because apparently the default centos config is invalid!
  
  - name: oracle-recommended security limits
    lineinfile:
      dest: /etc/security/limits.conf
      state: present
      line: "{{ item }}"
    with_items:
      - "oracle  soft   nproc   16384"
      - "oracle  hard   nproc   16384"
      - "oracle  soft   nofile  65536"
      - "oracle  hard   nofile  65536"
      - "oracle  soft  memlock 44501292"
      - "oracle  hard  memlock 44501292"