---

# Configuracion del sistema de archivos.
#7.1 Configuracion inicial.
#7.1.1 Configuracion del sistema de archivos.
  - name: 7.1.1.1.1 Deshabilitar el FileSystem cramfs
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.2 Deshabilitar el FileSystem freevxfs
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install freevxfs(\\s|$)"
      line: "install freevxfs /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.3 Deshabilitar el FileSystem jffs2
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install jffs2(\\s|$)"
      line: "install jffs2 /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.4 Deshabilitar el FileSystem hfs
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfs(\\s|$)"
      line: "install hfs /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.5 Deshabilitar el FileSystem hfsplus
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfsplus(\\s|$)"
      line: "install hfsplus /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.6 Deshabilitar el FileSystem squashfs
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      create: yes
    become: true
    
  - name:7.1.1.1.7 Deshabilitar el FileSystem udf
      lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      create: yes
    become: true
    
#7.1.2 Configurar Actualizaciones de Software.
#7.1.3 Configurar el boot de manera segura (Secure Boot Settings).
#7.1.4 Hardening adicional para procesos.
#7.1.5 Warning Banners.
#7.1.6 Asegurarse de que se hayan instalado actualizaciones, parches y software de seguridad
  
