---

# tasks file

#7.1 Configuración inicial.

#7.1.1 Configuración del sistema de archivos.

#7.1.1.1 Deshabilitar filesystems que no se usan

  - name: 7.1.1.1.1 Deshabilitar el FileSystem cramfs
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install cramfs(\\s|$)"
      line: "install cramfs /bin/true"
      create: yes
    
  - name: 7.1.1.1.2 Deshabilitar el FileSystem freevxfs
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install freevxfs(\\s|$)"
      line: "install freevxfs /bin/true"
      create: yes
    
  - name: 7.1.1.1.3 Deshabilitar el FileSystem jffs2
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install jffs2(\\s|$)"
      line: "install jffs2 /bin/true"
      create: yes
    
  - name: 7.1.1.1.4 Deshabilitar el FileSystem hfs
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfs(\\s|$)"
      line: "install hfs /bin/true"
      create: yes
    
  - name: 7.1.1.1.5 Deshabilitar el FileSystem hfsplus
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install hfsplus(\\s|$)"
      line: "install hfsplus /bin/true"
      create: yes
    
  - name: 7.1.1.1.6 Deshabilitar el FileSystem squashfs
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install squashfs(\\s|$)"
      line: "install squashfs /bin/true"
      create: yes
    
  - name: 7.1.1.1.7 Deshabilitar el FileSystem udf
    lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install udf(\\s|$)"
      line: "install udf /bin/true"
      create: yes

#7.1.1.2 Crear una partición separada para /tmp
#7.1.1.3 Configurar la opción nodev para la partición /tmp
#7.1.1.4 Configurar la opción nosuid para la partición /tmp
#7.1.1.5 Configurar la opción noexec para la partición /tmp
#7.1.1.6 Crear una partición separada para /var
#7.1.1.7 Crear una partición separada para /var/tmp
#7.1.1.8 Configurar la opción nodev para la partición /var/tmp
#7.1.1.9 Configurar la opción nosuid para la partición /var/tmp
#7.1.1.10 Configurar la opción noexec para la partición /var/tmp
#7.1.1.11 Crear una partición separada para /var/log
#7.1.1.12 Crear una partición separada para /var/log/audit de 10 GB
#7.1.1.13 Crear una partición separada para /home
#7.1.1.14 Configurar la opción nodev para la partición /home
#7.1.1.15 Configurar la opción nodev para la partición /dev/shm
#7.1.1.16 Configurar la opción nosuid para la partición /dev/shm
#7.1.1.17 Configurar la opción noexec para la partición /dev/shm
#7.1.1.18 Configurar la opción nodev para particiónes de medios extraíbles (cdrom, floppy,etc)
#7.1.1.19 Configurar la opción noexec para particiónes de medios extraíbles (cdrom, floppy,etc)
#7.1.1.20 Configurar la opción nosuid para particiónes de medios extraíbles (cdrom, floppy,etc)
#7.1.1.21 Setear Sticky Bit en todos los Directorios con permiso de escritura
  
#7.1.2 Configurar Actualizaciónes de Software.

  - name: 7.1.2.1 Configurar la conexión a los repositorios de RPM de la Red Hat Network (RHN)
    command: subscription-manager identity
    changed_when: no
    failed_when: no
   
  - name: 7.1.2.2 Verificar que gpgcheck este activado globalmente
    replace:
      name: /etc/yum.conf
      regexp: "^gpgcheck=0"
      replace: "gpgcheck=1"
    
  - name: 7.1.2.3 Verificar si la clave GPG Red Hat está Instalada
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
 
  - name: 7.1.2.4 Obtener actualizaciónes de paquetes con yum
    yum: 
      list: updates 
    register: yum_output
  
#7.1.3 Configurar el boot de manera segura (Secure Boot Settings).

  - name: 7.1.3.1 Asegúrese de que los permisos en la configuración del bootloader estén configurados
    file:
      path: /boot/grub2/grub.cfg 
      owner: root
      group: root
      mode: 0600

#7.1.4 Hardening adiciónal para procesos.

  - name: 7.1.4.1 Restringir los Core Dumps
    lineinfile:
      state: present
      dest: /etc/security/limits.conf
      regexp: '^#?\\*.*core'
      line: '*                hard    core            0'
      insertbefore: '^# End of file'
  
  - name: 7.1.4.1 Restringir los Core Dumps
    sysctl:
      name: fs.suid_dumpable
      value: '0'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
        
  - name: 7.1.4.2 Habilitar la región Randomized Virtual Memory
    sysctl:
      name: kernel.randomize_va_space
      value: '2'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
      
#7.1.5 Warning Banners.

  - name: 7.1.5.1 Configurar Warning Banners
    template:
      src: templates/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
  
  - name: 7.1.5.1 Configurar Warning Banners
    template:
      src: templates/issue.j2
      dest: /etc/issue
      owner: root
      group: root
      mode: 0644
  
  - name: 7.1.5.1 Configurar Warning Banners
    template:
      src: templates/issue.net.j2
      dest: /etc/issue.net
      owner: root
      group: root
      mode: 0644

#7.1.6 Asegurarse de que se hayan instalado actualizaciónes, parches y software de seguridad. Idem 7.1.2.4
